---
sidebar: sidebar 
permalink: aws/reference_whats_new_cloud_volumes_aws.html 
keywords: Cloud Volumes Service for AWS, what's new, features, enhancements 
summary: NetApp은 새로운 기능과 개선사항을 제공하기 위해 AWS용 Cloud Volumes Service를 정기적으로 업데이트합니다. 
---
= Cloud Volumes Service for AWS의 새로운 기능
:toc: macro
:hardbreaks:
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp은 새로운 기능과 개선사항을 제공하기 위해 AWS용 Cloud Volumes Service를 정기적으로 업데이트합니다.



== 2021년 2월

* 이제 새로운 Cloud Volumes API('PerformanceMetrics')를 사용하여 IOPS, 대역폭, 지연 시간 등의 성능 통계를 검색할 수 있습니다. 자세한 내용은 을 참조하십시오 link:reference_cloud_volume_apis.html["Cloud Volumes API"^].




== 2020년 7월

* Cloud Volumes Service는 이제 /16과 /28 사이의 보다 넓은 RFC 1918 사설 네트워크 범위를 지원합니다. 이전에는 28개 범위만 지원됩니다.
* 이제 '동기화' 기능이 Cloud Sync UI와 직접 통합되어 향상된 기능을 제공합니다.
* 볼륨은 API 호출을 통해 NSFv3, NFSv4.1 및 NFSv3과 NFSv4.1 모두로 변환될 수 있습니다.
* API 예제 및 샘플 Python 스크립트가 v2 API로 업데이트되었습니다. link:reference_cloud_volume_apis.html["Cloud Volumes API 를 참조하십시오"].
* 이제 NFSv4.1 볼륨에 대해 ACL이 활성화됩니다.
* Cloud Volumes Service는 이제 SOC 2 Type 1로 인증되었습니다.
* Cloud Volumes Service는 현재 싱가포르에서 사용 가능합니다(AP-동남동-1).




== 2020년 3월

* Cloud Volumes Service는 이제 NFSv3 및 NFSv4.1 마운트의 경우 최대 1MiB의 I/O 크기를 지원합니다. 이전에는 최대 입출력 크기가 64KiB였습니다. I/O 크기를 늘리면 일부 워크로드의 성능이 향상될 수 있습니다. I/O 크기를 늘리려면 마운트 옵션 "rsize" 및/또는 "wsize"를 사용합니다. 예를 들어, mount -o nfsvers=4.1, rsize=1048576, wsize=1048576 172.25.0.4:/vol1/mnt/CV"를 사용합니다




== 2020년 2월

* Cloud Volumes Service는 현재 AWS 마켓플레이스에서 용량제(pay as you go) 방식으로 이용할 수 있습니다. 자세한 내용은 마켓플레이스 목록을 참조하십시오. https://aws.amazon.com/marketplace/pp/B0848MXK74[]원래 월 및 연간 구독 계획은 계속 사용할 수 있습니다.




== 2020년 1월

* 이제 Cloud Volumes Service는 여러 네트워크 연결을 동시에 사용하여 성능을 향상시키는 SMB 다중 채널을 지원합니다. 다중채널 은 Windows 클라이언트에서 기본적으로 활성화되지만 EC2 인스턴스는 RSS(Receive Side Scaling)를 지원하는 네트워크 어댑터를 사용해야 합니다.
* 이제 Cloud Volumes Service 사용자 인터페이스에서 스냅샷에서 볼륨을 되돌릴 수 있습니다. 따라서 클라이언트를 다시 마운트하지 않고도 볼륨을 시점 스냅샷으로 되돌릴 수 있습니다. 을 참조하십시오 link:task_reverting_volume_to_snapshot.html["스냅샷에서 볼륨을 되돌리는 중입니다"] 를 참조하십시오.

